stages:
  - build
  - scan

variables:
  # Can't compose variables with user-defined ones, so we repeat ourselves :'(
  # See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1809
  PROXY_REGISTRY: nexus.itsf.io:5005

  IMAGE_REGISTRY: nexus.itsf.io:5004
  IMAGE_BASE_NAME: nexus.itsf.io:5004/$CI_PROJECT_PATH
  IMAGE_DEPS: nexus.itsf.io:5004/$CI_PROJECT_PATH:deps

  PRE_COMMIT_IMAGE: nexus.itsf.io:5004/docker/pre-commit:latest
  SCAN_DEPS_IMAGE: nexus.itsf.io:5004/it4nw/libs/deps-scanner:latest

.only: &only
  only:
    - merge_requests
    - master
    - tags
    - develop

build:
  stage: build
  image: docker:git
  <<: *only
  services:
    - docker:stable
  tags:
    - docker
  before_script:
    - docker login $IMAGE_REGISTRY -p $NEXUS_PASSWORD -u $NEXUS_USER
    - docker login $PROXY_REGISTRY -p $NEXUS_PASSWORD -u $NEXUS_USER
  script:
    - docker pull $IMAGE_DEPS || true
    - docker build --pull --cache-from $IMAGE_DEPS -t $IMAGE_DEPS --target venv .
    - docker push $IMAGE_DEPS
    - docker pull $IMAGE_BASE_NAME || true
    - docker build --pull --cache-from $IMAGE_DEPS --cache-from $IMAGE_BASE_NAME -t $IMAGE_BASE_NAME .
    - docker push $IMAGE_BASE_NAME


pre_commit:
  stage: build
  image: $PRE_COMMIT_IMAGE
  <<: *only
  script:
    - pre-commit run --all-files --color always --show-diff-on-failure


scan-deps:
  stage: scan
  image: $SCAN_DEPS_IMAGE
  allow_failure: true
  script:
    - scan-deps poetry.lock pyproject.toml | comment-gitlab
  only:
    - merge_requests
