stages:
  - build

variables:
  # Can't compose variables with user-defined ones, so we repeat ourselves :'(
  # See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1809
  IMAGE_PULL_REGISTRY: nexus.itsf.io:5005
  IMAGE_PULL_BASE_NAME: nexus.itsf.io:5005/$CI_PROJECT_PATH

  IMAGE_PUSH_REGISTRY: nexus.itsf.io:5004
  IMAGE_PUSH_BASE_NAME: nexus.itsf.io:5004/$CI_PROJECT_PATH

build:
  stage: build
  image: docker:git
  services:
  - docker:stable
  tags:
    - docker
  before_script:
    - docker login $IMAGE_PUSH_REGISTRY -p $NEXUS_PASSWORD -u $NEXUS_USERNAME
    - docker login $IMAGE_PULL_REGISTRY -p $NEXUS_PASSWORD -u $NEXUS_USERNAME
  script:
    - docker pull $IMAGE_PULL_BASE_NAME || true
    - docker build --pull --cache-from $IMAGE_PULL_BASE_NAME -t $IMAGE_PUSH_BASE_NAME .
    - docker push $IMAGE_PUSH_BASE_NAME
